[[services]]
name = "be"
source = "packages/wordle-be"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build:be"

[services.deploy]
startCommand = "npm run start:be"
healthcheckPath = "/health"