[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && npm install && npm run build:be"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10