[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build:be"

[deploy]
startCommand = "npm run start:be"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10